const express = require("express");
const router = express.Router();
const hospitalsController = require('../controllers/hospitalsController');
const hospitalValidator = require("../validations/hospitalValidator");
const jwToken = require("../validations/jwtValidation");
router.get('/hospital', hospitalsController.getHospital);
router.get('/hospitals', jwToken.validateToken, hospitalsController.getHospitals);
router.post('/hospital', hospitalValidator.add, hospitalsController.postHospital);
router.post("/login", hospitalValidator.id, hospitalsController.getLogin);
router.put('/hospital', hospitalValidator.update, hospitalsController.postHospital);
router.delete('/hospital', hospitalValidator.id, hospitalsController.deleteHospital);
module.exports = router;
